### PR TITLE
Support rotated tiles

### PR DESCRIPTION
**Pull request by lapinozz**

### CODE REVIEW

**Comment by makian123** [comment]
Why thruster info not in block archetypes json?

**Comment by lapinozz** [comment]
> Why thruster info not in block archetypes json?

Not sure if machines should be blocks

**Comment by makian123** [comment]
> > Why thruster info not in block archetypes json?
> 
> Not sure if machines should be blocks

i mean why not, you can break them, they have their state (work done, power...) and tilemap index, (last part is in the json)

**Comment by lapinozz** [comment]
> > > Why thruster info not in block archetypes json?
> > 
> > 
> > Not sure if machines should be blocks
> 
> i mean why not, you can break them, they have their state (work done, power...) and tilemap index, (last part is in the json)

Because you can place them over blocks

**Comment by makian123** [comment]
> > > > Why thruster info not in block archetypes json?
> > > 
> > > 
> > > Not sure if machines should be blocks
> > 
> > 
> > i mean why not, you can break them, they have their state (work done, power...) and tilemap index, (last part is in the json)
> 
> Because you can place them over blocks

Separate machine structure and json?

**Review by makian123 — APPROVED** [review]
Lgtm

**Pull request merged**
